In [9]:
import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder

In [10]:
dados = pd.read_csv('E:/Mestrado Matérias/2 MÓDULO/Machine Learning/LISTA 2/Q6.csv')

In [11]:
dados

Dia       Tempo Temperatura Umidade  Vento Joga
0    D1  Ensolarado      Quente    Alta  Fraco  Não
1    D2  Ensolarado      Quente    Alta  Forte  Não
2    D3     Nublado      Quente    Alta  Fraco  Sim
3    D4     Chuvoso       Média    Alta  Fraco  Sim
4    D5     Chuvoso        Fria  Normal  Fraco  Sim
5    D6     Chuvoso        Fria  Normal  Forte  Não
6    D7     Nublado        Fria  Normal  Forte  Sim
7    D8  Ensolarado       Média    Alta  Fraco  Não
8    D9  Ensolarado        Fria  Normal  Fraco  Sim
9   D10     Chuvoso       Média  Normal  Fraco  Sim
10  D11  Ensolarado       Média  Normal  Forte  Sim
11  D12     Nublado       Média    Alta  Forte  Sim
12  D13     Nublado      Quente  Normal  Fraco  Sim
13  D14     Chuvoso       Média    Alta  Forte  Não

Separandos os dados 

In [12]:
X_dados = dados.iloc[:,1:5].values

X_dados

array([['Ensolarado', 'Quente', 'Alta', 'Fraco'],
       ['Ensolarado', 'Quente', 'Alta', 'Forte'],
       ['Nublado', 'Quente', 'Alta', 'Fraco'],
       ['Chuvoso', 'Média', 'Alta', 'Fraco'],
       ['Chuvoso', 'Fria', 'Normal', 'Fraco'],
       ['Chuvoso', 'Fria', 'Normal', 'Forte'],
       ['Nublado', 'Fria', 'Normal', 'Forte'],
       ['Ensolarado', 'Média', 'Alta', 'Fraco'],
       ['Ensolarado', 'Fria', 'Normal', 'Fraco'],
       ['Chuvoso', 'Média', 'Normal', 'Fraco'],
       ['Ensolarado', 'Média', 'Normal', 'Forte'],
       ['Nublado', 'Média', 'Alta', 'Forte'],
       ['Nublado', 'Quente', 'Normal', 'Fraco'],
       ['Chuvoso', 'Média', 'Alta', 'Forte']], dtype=object)

In [13]:
y_dados = dados.iloc[:,-1].values

y_dados

array(['Não', 'Não', 'Sim', 'Sim', 'Sim', 'Não', 'Sim', 'Não', 'Sim',
       'Sim', 'Sim', 'Sim', 'Sim', 'Não'], dtype=object)

Transformando os dados categóricos em numéricos

In [14]:

label_encoder_tempo = LabelEncoder()
label_encoder_temperatura = LabelEncoder()
label_encoder_umidade = LabelEncoder()
label_encoder_vento = LabelEncoder()

In [15]:

X_dados[:,0] = label_encoder_tempo.fit_transform(X_dados[:,0])
X_dados[:,1] = label_encoder_temperatura.fit_transform(X_dados[:,1])
X_dados[:,2] = label_encoder_umidade.fit_transform(X_dados[:,2])
X_dados[:,3] = label_encoder_vento.fit_transform(X_dados[:,3])

X_dados

array([[1, 2, 0, 1],
       [1, 2, 0, 0],
       [2, 2, 0, 1],
       [0, 1, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 1, 0],
       [2, 0, 1, 0],
       [1, 1, 0, 1],
       [1, 0, 1, 1],
       [0, 1, 1, 1],
       [1, 1, 1, 0],
       [2, 1, 0, 0],
       [2, 2, 1, 1],
       [0, 1, 0, 0]], dtype=object)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X_dados, y_dados, test_size = 0.3, random_state=0)

In [17]:
naive_dados = GaussianNB() #Distribuição normal
#Treinando o algoritmo

naive_dados.fit(X_dados,y_dados)

#Acurácia do modelos
naive_dados.score(X_dados,y_dados)

0.8571428571428571

<h5>Previsão de um novo dado
    

In [18]:
#chuvoso(0), quente(2), alta(0) e forte(0)

previsao = naive_dados.predict([[0,2,0,0]])


In [19]:
previsao

array(['Não'], dtype='<U3')

In [20]:
#Classes

naive_dados.classes_

array(['Não', 'Sim'], dtype='<U3')

In [21]:
#Atributos por classe

naive_dados.class_count_

array([5., 9.])

In [22]:
#Propriedade a priori

naive_dados.class_prior_

array([0.35714286, 0.64285714])